### ISSUE TITLE
Create a docker version for unraid

### ISSUE THREAD

**Issue by westy** [b-m-f/WirtBot#123]
As discussed briefly on your Reddit post it'd be nice if you could sort out a version that could run in a docker on unraid.

Cheers

**Comment by b-m-f** [comment]
This needs:

- single docker image: DONE
- image  build in dockerhub
- updated docs
- update ansible scripts
  - provide ansible upgrade path from old setup
  - OR update the installer to take backups and require a new install

**Comment by b-m-f** [comment]
@westy would you mind taking a look at https://github.com/b-m-f/WirtBot/pull/124/files ?

Do the [Dockerfile](https://github.com/b-m-f/WirtBot/pull/124/files#diff-4cf6ddfc2326a2466b16aee64e7f15cd207ed612a01ec2f4bff2438b4a68038e) and [Nginx config](https://github.com/b-m-f/WirtBot/pull/124/files#diff-16721127b1a5ac2e16c2962c6fa9ca36a47df7a6e76b94d5ee7541d5febf6122) look good to you?

**Comment by westy** [comment]
Hi @b-m-f,

I'm no Docker expert I'm afraid, just a keen unraid user with a need to replace Teamviewer for supporting my families computers!

The unraid forums are very active, so you may be able to find some info or help there perhaps: https://forums.unraid.net/forum/58-docker-engine/

I would also suggest trying to build a simple unraid box with whatever hardware you may have lying about. It really doesn't need much. I am also willing to help test if you'd like.

Cheers

**Comment by b-m-f** [comment]
@westy the MR will land in master in a few minutes.

Installing **Unraid** for verification is too much of an edge case for me. 

But the Docker image is there and it includes, WirtBot with DashBoard and WireGuard.

If youd like to ask for more support on the Unraid forums here is what is necessary:

- Linux Kernel 5.6 or WireGuard Kernel modules
- `NET_ADMIN` capabilities for WirtBot container to start the WireGuard interface (stopping the container removes the interface again)
- Another image with CoreDNS if youd like to use the DNS feature

Check the new setup docs at https://wirtbot.com/documentation/setup#docker for an example `docker-compose.yml`

**Comment by westy** [comment]
Thanks @b-m-f, I really appreciate your efforts and the quick turnaround.

I'll try and find time to have a look over the next few days.
I've never tried setting up a docker template myself on unraid, but I guess now's the time to learn :)

**Comment by b-m-f** [comment]
Let me know if you get stuck on docker things!

If you get WireGuard into the Kernel I am sure itll be straight forward to get the rest done!

**Comment by b-m-f** [comment]
Closing this
