### ISSUE TITLE
SSH Port issue installation

### ISSUE THREAD

**Issue by nksky** [b-m-f/WirtBot#131]
Hi,

I am running my SSH port on a different port to 22, eg 1301. I think this is stopping my installation, I am receiving these errors....

> Configuration written to ./wirt-installer.config.json
TypeError: Cannot read property 'v4' of undefined
    at generateDNSFile (/usr/lib/node_modules/@wirtbot/installer/dist/installer.js:25:34)
    at install (/usr/lib/node_modules/@wirtbot/installer/dist/installer.js:514:31)
    at async main (/usr/lib/node_modules/@wirtbot/installer/dist/installer.js:547:13)
Installation complete

Can you advise? Thank you.

**Comment by b-m-f** [comment]
hi @nksky,

I will check and let you know later today

**Comment by nksky** [comment]
Thank you. Looking forward to trying the platform.

**Comment by b-m-f** [comment]
hi @nksky ,

So the bug should be fixed in `@wirtbot/installer@1.4.2`.

But there is another thing. 
The installer assumes that you have a clean VPS and will apply all security hardening and firewalls based on that.

If you have already got a server set up maybe you'd be better off with using the docker based install?

**Comment by b-m-f** [comment]
To support custom SSH ports this would need to be added to the installer if youd like to add this functionality.

But be aware that the Firewall is very tight and might block anything else running on the server.

Check the `nftables.conf.j2` file in the repo for more info :)

**Comment by qimmiq** [comment]
i would be interessted in custom ssh port aswell :) 
beside that im also running an ssh port not being 22 ... i throw that error 'WebAssembly key generation: CompileError: WasmCompile: Wasm decoding failed: mutable globals cannot be exported @+1116
Installation complete'

**Comment by b-m-f** [comment]
@qimmiq ,

which Version of node do you have installed?

3 things will need to be added for custom SSH ports:

- question about port in installer
- pass port to ansible runner
- set port in sshd config in the ansible task

**Comment by qimmiq** [comment]
hey @b-m-f thanks for that quick replay. 
since i did a fresh whipe of my vps and i still got the error 
i think it sth nothing related to ssh. so my node is v8.10.0

**Comment by b-m-f** [comment]
@qimmiq 
Can you upgrade to Nodev14?

I will add this to the docs. Seems needed to execute the WASM for key Generation locally.

**Comment by b-m-f** [comment]
@qimmiq Were you able to get it running?

**Comment by qimmiq** [comment]
@b-m-f thanks for checking back ... i did update ... which worked. 
but i got stuck at another point. couldnt get a connection. maybe i did sth wrong. but didnt try again

**Comment by b-m-f** [comment]
@qimmiq Ah, too bad. Any thing that was unclear during the setup. 
Could you tell me what connection wasnt working? 

Trying to make sure there isnt some bug lurking  :)

**Comment by qimmiq** [comment]
let me try it again ... in some days. 
i will reformat my vps :D and document step by step

**Comment by b-m-f** [comment]
@qimmiq thanks for the effort!

You can always ping me here for questions!

**Comment by nksky** [comment]
> @qimmiq Were you able to get it running?
> @nksky how about you?

Sorry for my late reply on this, No I wasn't able to get it going, Im getting with the port and in turn Ansible error code 4. Have the port options being put in to the installer yet?

**Comment by b-m-f** [comment]
@nksky Nope,
I am currently working on other things.

But if youd like to give it a go I can give you some pointers

**Comment by qimmiq** [comment]
@b-m-f yes please ...  i give it a try in a spare minute :D

**Comment by nksky** [comment]
> @b-m-f yes please ... i give it a try in a spare minute :D

I am busy with work, but will help you out, PM me and I can give you access to my server if you'd like to use it as a test bench.

**Comment by b-m-f** [comment]
@nksky @qimmiq 

Here is a break down of what is needed:

- New question to ask for update https://github.com/b-m-f/WirtBot/blob/master/Installer/index.js#L13
- Same question during installation https://github.com/b-m-f/WirtBot/blob/master/Installer/index.js#L37
- Make sure the port gets passed into https://github.com/b-m-f/WirtBot/blob/master/Installer/src/ansible.js#L4 correctly
- Pass the **ssh_port** variable to ansible from  https://github.com/b-m-f/WirtBot/blob/master/Installer/src/ansible.js#L4 
- Use variable in [firewall](https://github.com/b-m-f/WirtBot/blob/master/Installer/ansible/tasks/templates/nftables.conf.j2)
- Use variable in [fail2ban](https://github.com/b-m-f/WirtBot/blob/master/Installer/ansible/tasks/templates/fail2ban.jail.local.j2)
- Use variable in [SSH daemon configuration](https://github.com/b-m-f/WirtBot/blob/master/Installer/ansible/tasks/sshd_config.yml)

I believe that this should be it. 

22 should also be the default. So the question should probably be `Do you want to specify a different SSH port?` followed by a prompt for the port. Check out the [backup questions](https://github.com/b-m-f/WirtBot/blob/master/Installer/index.js#L73) that work similarly.

**Comment by b-m-f** [comment]
Hi @nksky ,

Still interested in giving this a go?

**Comment by nksky** [comment]
Absolutely, I will try later tonight and give you an update. Thanks for
this.

**Comment by b-m-f** [comment]
Hi @nksky ,

In case you still have a branch around I think its time to delete it :)

Check https://wirtbot.com/announcements/update-4.html#new-setup-flow for info on the new setup which should easily support the custom SSH port now
