### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by qimmiq** [b-m-f/WirtBot#138]
As discussed here we go again. 

Fresh VPS 
node > 14
install with root. 

When setting up. 
IP of your server  = VPS? 
Public Key = Computer im setting up with 
"If you have an SSH key on the server during initial setup" = its the ssh key from my computer i use to ssh into my vps (same as public key from above) 

```
PLAY [all] *********************************************************************
 

TASK [Gathering Facts] *********************************************************
 
fatal: [**.***.**.*** ]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@**.***.**.*** : Permission denied (publickey,password).", "unreachable": true}
 

PLAY RECAP *********************************************************************
 
**.***.**.***              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
 

 
Ansible exited with error code: 4
Installation complete
```

so did i miss understand sth ?! :)

**Comment by b-m-f** [comment]
Ok, 

looking at your info this could be a bug in the installer.

Maybe you could add another step that asks whether or not Password or PubKey authentification should be used for the setup.

This would need then to be passed to [this function](https://github.com/b-m-f/WirtBot/blob/master/Installer/src/ansible.js#L4 ) where ansible can be called with the correct mode.

**Comment by nksky** [comment]
I am having similar errors on this.

**Comment by b-m-f** [comment]
Hi @qimmiq 
Please check https://wirtbot.com/announcements/update-4.html#new-setup-flow.

There is now a less opinionated setup flow using only the containerized Core and Interface.

Will close this issue. Please open a new one should you encounter any problems
