### ISSUE TITLE
Initial "Import Backup" Errors

### ISSUE THREAD

**Issue by dickiesanders** [b-m-f/WirtBot#156]
I was able to get WirtBot installed, configure my Wireguard client, and I can reach the [wirtbot.wirt.internal](wirtbot.wirt.internal) but when I try to import the initial backup file to "control" my setup I am receiving the following console errors:

`TypeError: Cannot create property 'version' on string {"version":1.0,"server":{"ip":{"v4":["X","X","X","X"]},"port":10101,"keys":{"private":"=","public":""},"subnet":{"v4":"10.10.0.","v6":"1010:1010:1010:1010:"}},"devices":[{"ip":{"v4":2},"name":"Change me","keys":{"private":"","public":""},"type":"Linux"}],"keys":{"private":"","public":""}}`

and 

`Uncaught (in promise) Error: Error when upgrading your backup from beta version to 1.0`

**Comment by b-m-f** [comment]
@dickiesanders Interesting.

I am currently working on v2 which removes the installer and changes the setup flow.

It will require more work on the machine as the ansible script is gone.

But to fix this for now can you try to manually add `"version":1.5.8` to the backup file before importing it?

**Comment by dickiesanders** [comment]
@b-m-f  - Tried to update the version in my json backup file, but I received the same error as before when importing the file.

**Comment by b-m-f** [comment]
Interesting. Can you check the version of the installer you have?

There was a bug in older versions where the backup was given a doubly-stringified string -> https://github.com/b-m-f/WirtBot/pull/113

**Comment by dickiesanders** [comment]
I assume this means I have version 1.5.6 of the installer.
<img width="776" alt="Screen Shot 2021-02-16 at 1 08 22 PM" src="https://user-images.githubusercontent.com/12834880/108103642-372c1180-7058-11eb-9100-21731c15a7a7.png">

**Comment by b-m-f** [comment]
Seems like the bug is in 1.5.6 but on the installer side.

Found 
```
const interfaceState = JSON.stringify(JSON.stringify({
                version: 1.1,
                server,
                devices: [device],
                keys: signingKeys
            }));
```
As you can see it is stringified twice.

Could you parse it locally once?
Simply type `node` in the terminal and then run `JSON.parse(CONTENT_OF_FILE)`.

Then simply paste the output back into a file and import that on the interface.

**Comment by b-m-f** [comment]
No need to fix code here, as I have removed the installer for maintenance ease.

Here is a more thorough update https://wirtbot.com/announcements/update-4.html :)

**Comment by dickiesanders** [comment]
@b-m-f  - Thank you for your quick replies!

I just refreshed the doc pages and saw the updates from above. I'll kill my setup (close this thread) and start over with the docker and docker-compose setup, which I wanted to use initially. :)

**Comment by b-m-f** [comment]
@dickiesanders  You are very welcome. Hope it'll work for you.
The latest version 2.2.2 is currently running through the build pipeline
