### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#182]
I`m newbie to wireguard, docker etc. Followed the [installation guide](https://wirtbot.com/documentation/setup.html#initial-setup), but on the step  "Setting up your network" faced with the next errors.
![screen_2021 03 14 002](https://user-images.githubusercontent.com/15985877/111078111-0f1fb900-8505-11eb-9f1a-5d1d39f53777.png)

Browser console:
![screen_2021 03 14 001](https://user-images.githubusercontent.com/15985877/111078114-121aa980-8505-11eb-9072-8df08d8b5d7a.png)

**Comment by b-m-f** [comment]
Hi @squromiv ,

can you please paste you docker-compose.yml file?

Make sure to anonymize it.

Also, did you make sure to set the `ALLOWED_ORIGIN` to `http://51.XXX` ?

**Comment by squromiv** [comment]
Something like that (changed IP of the VPS to fake)
`version: "3.4"

services:
  WirtBot:
    image: bmff/wirtbot:latest
    container_name: WirtBot
    ports:
      - 53:53
      - 80:80
      - 3030:3030
      - 10101:10101/udp
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    environment:
      - "ALLOWED_ORIGIN=http://51.43.118.127/"
      - "DNS_UID=1003"
      - "DNS_GID=1003"
      - "INTERFACE_UID=1002"
      - "INTERFACE_GID=1002"
      - "CORE_UID=1001"
      - "CORE_GID=1001"
    volumes:
      - wireguard-data:/etc/wireguard
      - coredns-data:/etc/coredns
volumes:
  wireguard-data:
  coredns-data:`

**Comment by b-m-f** [comment]
@squromiv please set the API endpoint to the Allowed origin as well.

You can find this at the top of the dashboard.

The default is 'wirtbot.wirt.internal', but only works if already connected.

**Comment by squromiv** [comment]
> but only works if already connected
I`m so sorry, because don`t understand clearly, how it works.
When I click "Connect" and redirected to dashboard - does it mean, that I am connected?
![screen_2021 03 15 0024](https://user-images.githubusercontent.com/15985877/111200820-30e77180-85d3-11eb-8e2a-a7288ef95f6d.png)

**Comment by squromiv** [comment]
So, I have changed to this configuration
![888](https://user-images.githubusercontent.com/15985877/111207406-a440b180-85da-11eb-85a3-34628d6108d2.png)

**Comment by b-m-f** [comment]
Hi @squromiv,

can you please remove the `http://` from `http://51.43.118.127:3030`.

Also thanks for the screenshots. 

By connected I mean connected to the Wirtbot via WireGuard.

Right now you are still in the setup stage, where you communicate with the Host machine of the WirtBot unencrypted over normal network interfaces.

Once the setup is done and you connect via the WireGuard configs you will be able to reach the WirtBot at `http://wirtbot.wirt.internal`

**Comment by squromiv** [comment]
I have removed `http://` and have the same errors. Tried in different browsers.

**Comment by b-m-f** [comment]
Could you attach the console error again?

Please also try removing the trailing slash from "ALLOWED_ORIGIN=http://51.43.118.127/"

**Comment by squromiv** [comment]
Could you also make some modifications to the setup page? - A button like "Save settings" or "Add server". Because it is quite annoying to see such errors every time a user changes one symbol.

**Comment by squromiv** [comment]
> Could you attach the console error again?

![screen_2021 03 16](https://user-images.githubusercontent.com/15985877/111279592-e48c4800-864b-11eb-95f9-e2cd5e2b8664.png)

**Comment by b-m-f** [comment]
Okay nice. New error message. 401 unauthorized.

This could mean two things:

- you restarted the WirtBot container without entering the public key from the DashBoard as an environment variable -> this generates a new keypair, meaning your dashboard is using outdated keys now : https://wirt.network/documentation/setup.html#setting-up-your-network
- An error in the Core -> check the logs with `docker logs -f WirtBot`

**Comment by b-m-f** [comment]
@squromiv you forgot to black out the IP on the last Screenshot!

**Comment by squromiv** [comment]
> dashboard is using outdated keys now

Great support. I deleted current docker container, recreated it. Copied keypair-string from logs, modified "WirtBot API host" and "IP address" to IP of my VPS. And finally

![screen_2021 03 16 001](https://user-images.githubusercontent.com/15985877/111302851-ef070b80-8664-11eb-8659-a8c1bb39a8a7.png)

**Comment by squromiv** [comment]
But faced with another problem:
Added a device->downloaded config->imported on client machine successfully

Added a device->checked the box "Routed"->downloaded config->importing on client fails

![screen_2021 03 16 001](https://user-images.githubusercontent.com/15985877/111305729-5d999880-8668-11eb-995d-e52b9c1b4d08.png)

![screen_2021 03 16 001_new](https://user-images.githubusercontent.com/15985877/111305545-23c89200-8668-11eb-9ab3-5cc68be5d8af.png)

Do i have to manually register the ipv6 address in order to route all my traffic through the VPS?

**Comment by b-m-f** [comment]
Hey @squromiv ,

first of all glad it worked.

For the IP I am actually not sure.
There might be a bug here. 

You would need the IPv6 equivalent of 0.0.0.0/0 in IPv4 in that config.

If you can figure that out and try it I can fix this in the config generation if that is the issue.

**Comment by squromiv** [comment]
> Please try to edit the config manually -> change that IPv6 to `::/0`

Ok. Downloaded *.conf file of client config, edited and import was successful. Let`s close this issue and discuss on [reddit](https://www.reddit.com/r/WirtBot/comments/m0j309/after_about_a_year_of_development_wirtbot_is_now/), because i have some other questions.
