### ISSUE TITLE
Incorrect IPV6 address in generated config files for "Routed" mode

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#184]
It looks like
`AllowedIPs = 0.0.0.0/0,0001:0000:0000:0000:0000:0000:0000/0`

But native wireguard clients don`t support this format. So importing such a profile fails.

**Comment by dickiesanders** [comment]
Can you try: 0.0.0.0/0, ::/0

**Comment by b-m-f** [comment]
@dickiesanders thats the correct solution :)

The problem is at https://github.com/b-m-f/WirtBot/blob/master/Interface/src/lib/wireguard.js#L19
