### ISSUE TITLE
To ping subnet

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#190]
I can`t ping container subnet from host machine. This function works only in "docker exec -ti WirtBot /bin/bash". Should I set "network_mode: host" in docker-compose.yml, in order to ping?

**Comment by b-m-f** [comment]
Yes. The host machine is not part of the network unless `network_mode: host` is set.

Will add this to the FAQ. Cheers

**Comment by squromiv** [comment]
> Yes

Thanks a lot. I coudn`t understand what`s wrong in my set up.

So I`ve tried:
![screen_2021 03 31 007](https://user-images.githubusercontent.com/15985877/113158224-45b73c80-9244-11eb-8ffa-59484d4f09a8.png)
Unsuccesful
![screen_2021 03 31 008](https://user-images.githubusercontent.com/15985877/113158623-a0509880-9244-11eb-8df6-e5a03ea72d51.png)

**Comment by dickiesanders** [comment]
@squromiv - comment out or remove the "ports" section in your docker-compose.yml file. When using `network_mode: host` the port bindings do not matter.

**Comment by squromiv** [comment]
> comment out or remove the "ports" section

![screen_2021 03 31 009](https://user-images.githubusercontent.com/15985877/113162248-ca578a00-9247-11eb-9db9-aaf24160f61d.png)

**Comment by b-m-f** [comment]
Yup, this is not related to WirtBot, but your host machine. Try removing that section.

**Comment by squromiv** [comment]
Final docker-compose.yml
![screen_2021 03 31 0010](https://user-images.githubusercontent.com/15985877/113163359-c2e4b080-9248-11eb-8f38-85049fa422ab.png)
Container runs. But no ping from the host to subnet. What is wrong now?

**Comment by dickiesanders** [comment]
Would you mind sharing exactly what you are trying to test?  You won't be able to ping the container since you've bound the container network to your host network. i.e, open your browser to `HTTP://**HOST_IP**:80` and you should see the wirtbot webpage. 

Generally, when doing something port-specific with containers using `ping` is not the best utility for troubleshooting.

**Comment by b-m-f** [comment]
@squromiv 
If you want to ping Network clients from your Host machine - that is the machine running the WirtBot container - you will still need to set up the correct routing manually, see the [official WireGuard quickstart](https://www.wireguard.com/quickstart/).

Use `network_mode: host` is only making the interface available on the Host machine (and removes some networking layers for speed!) but all the wiring is only done inside the container.


This is also not a use case that the WirtBot is intended for. 
If you require this kind of setup, you might want to check out pure config generators and apply those configurations manually.


Thanks for all the screenshots and feedback though. Hope youll be able to build your network inside while staying inside the container as well :)

**Comment by b-m-f** [comment]
@dickiesanders thanks for helping out! :)

Will close this issue now @squromiv, since the wiring is outside the scope of WirtBot.
