### ISSUE TITLE
Restoring from backup goes wrong

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#200]
Configured Wirtbot --> set "ALLOWED_ORIGIN=http://wirtbot.wirt.internal" in docker-compose.yml   --> restarted container --> connected from client to host with Wireguard --> changed Wirtbot API host on dashboard to "wirtbot.wirt.internal" --> made backup of dashboard --> cleaned cookies in browser --> entered the dashboard by http://wirtbot.wirt.internal --> restored backup --> it said, that was restored successfully, field values were loaded --> in about 15 seconds dashboard page became  inaccessible (connection failed) --> "server.conf" (/var/lib/docker/volumes/wirtbot_wireguard-data/_data) lost all clients.

Retested several times.

**Comment by b-m-f** [comment]
Hm, interesting.

Have you tried to restart the WirtBot with `docker restart WirtBot` ?

I think I encountered a similar situation where all clients were dropped.

I believe that this will need some extended research into WireGuard and how the interface gets updated.

**Comment by squromiv** [comment]
> Have you tried to restart the WirtBot with `docker restart WirtBot`

Yep. No sense.

Also I noticed some error during restoring.
![vid2](https://user-images.githubusercontent.com/15985877/116861333-9cc97c00-ac0b-11eb-966d-11ede49db2f2.gif)

API host - wirtbot.wirt.internal:3030)
Address in address bar - wirtbot.wirt.internal
Docker-compose file - "ALLOWED_ORIGIN=http://wirtbot.wirt.internal"

So what does Wirbot not like???

**Comment by b-m-f** [comment]
Are there any errors in the console?

Could you let me know if the requests are sent to the correct API by checking the browsers network tab?

Maybe something is wrong there.

I already commented on another issue that I am super busy this week.
But I'll go deeper into the issues on the weekend.

**Comment by b-m-f** [comment]
Maybe you could also send me a backup file via email?
So I can test the exact same setup.

**Comment by b-m-f** [comment]
Hi @squromiv,

I have identified a possible issue and will try to resolve this today.

Will update you

**Comment by b-m-f** [comment]
Have release 2.7.0 which should hopefully fix this

**Comment by b-m-f** [comment]
Hi @squromiv ,

did you manage to try it out?

**Comment by squromiv** [comment]
Hi, Maximilian. Sorry I'm a little busy right now. Will test later.

**Comment by b-m-f** [comment]
No worries!

**Comment by b-m-f** [comment]
Hi @squromiv ,

I have introduced a new bug. Going to update this today and add a test case

**Comment by b-m-f** [comment]
Marking this as resolved @squromiv
