### ISSUE TITLE
MY Device port Static

### ISSUE THREAD

**Issue by oddife** [b-m-f/WirtBot#238]
can we have my device ports set to a specified port as I'm using it on oracle cloud and I have to open ports manually which creates a problem when I connect using the client as the port is randomly generated every time

**Comment by b-m-f** [comment]
So to clarify:

You want to add a port to a device configuration in the dashboard?

**Comment by oddife** [comment]
> So to clarify:
> 
> You want to add a port to a device configuration in the dashboard?

Yes so i can open that port when i configure the user

**Comment by b-m-f** [comment]
Okay.

I will take a look in the coming days.

If possible in Wireguard the Dashboard will need a design change to accommodate the amount of fields that will be present in a DeviceRow.

ETA: 2-3 weeks

**Comment by oddife** [comment]
I think it's possible in wire guard as pi VPN uses it 
thank you for the help appericated

**Comment by b-m-f** [comment]
Hi,

the feature will be release in version 3.1.0.

I will trigger the CI in a few minutes when the testing suite has finished.

The version should be release on dockerhub in the next few hours. 

Enjoy

**Comment by oddife** [comment]
Thank you very much you are the man sure its very late here in India were I live with do it tomorrow morning and let you know
