### ISSUE TITLE
Not saving settings

### ISSUE THREAD

**Issue by ShayBox** [b-m-f/WirtBot#26]
It's not saving Expert mode, Server name, or WirtBot installed, they get reset on refresh.

EDIT:
CORS problem when trying to check the WirtBot toggle, bypassing that leads to `TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'`

**Comment by b-m-f** [comment]
@ShayBox just rolled out DNS in cluster. I will fix this next!

**Comment by b-m-f** [comment]
Hi @ShayBox,

Saving the attributes should be fixed now.

Could you retest the WASM problem and provide some more info for me to reproduce this?

**Comment by b-m-f** [comment]
@ShayBox closing this. Please open a new issue if the problem persists
