### ISSUE TITLE
Use DebOps for config management

### ISSUE THREAD

**Issue by ypid** [b-m-f/WirtBot#61]
You stated it yourself on https://wirt.network/

> I have one job and I do it well.

You might want to checkout https://docs.debops.org/en/master/. We are a group of committed sysadmins who are putting down all our experience into DebOps so that you don’t have to. I am referring to this: https://github.com/b-m-f/Wirt/tree/master/ansible/tasks Do you really want to maintain that long term :) ?

PS: I am currently working on getting WireGuard support into DebOps.

**Comment by b-m-f** [comment]
@ypid Thanks for the idea.

I will give it a look and see how I could integrate it.

There is still a lot of customization that will be needed.

Could you gimme a quick rundown on how to apply them onto a secure base comming from DebOps?

**Comment by ypid** [comment]
There are a few ways. You could integrate debops as a git submodule into https://github.com/b-m-f/Wirt/tree/master/ansible. This way you stay fully in control. Then you could use Ansible inventory variables to do those things instead of your tasks doing them:

* Enable maintenance user for maintenance with ssh key provided
* Firewall only allows Port 22, 3030, Wireguard port 21212, 80 and 443
* installs certbot
* Install fail2ban
* install wireguard (you will need my role, currently at https://github.com/ypid/ansible-wireguard/tree/prepare-for-debops)

Than update the docs.

> secure base

BTW, `--ssh-common-args='-o StrictHostKeyChecking=no'` looks scary to me as we are talking about security.

**Comment by b-m-f** [comment]
@ypid Thank you. 

the Strict Host key checking is a good catch! thank you :)

I like the idea of integrating a common base, but I think I would wait a bit until your change is included into the master.

Could you ping me here when that is done? Thanks alot for all the info

**Comment by ypid** [comment]
Heads up, I guess I will do this in two steps. First I just want to solve my use case and gain experience from running WireGuard. Then I will leave the role laying a bit, not yet in DebOps master. Then in a second step, 2021, bring the role to perfection including extensive docs and into DebOps. Like https://docs.debops.org/en/master/ansible/roles/cryptsetup/index.html

So I guess I will ping you two times :)

**Comment by ypid** [comment]
All right, step 1 is working now. You may start using it. Step 2 will take a while (months to years).

**Comment by b-m-f** [comment]
@ypid I have removed ansible from the Project scope. So I will close this issue for now
