### ISSUE TITLE
Entering IPv4 deletes other settings

### ISSUE THREAD

**Issue by b-m-f** [b-m-f/WirtBot#86]
When first entering things like **additional DNS** or **MTU** and then the **IPv4**, the **MTU** and **additional DNS** get deleted.

Needs some investigation and a fix

**Comment by sdhiman99** [comment]
Hi! I'd like to take this up. To start with, can you guide me towards the required Component?

**Comment by b-m-f** [comment]
Hu @sdhiman99 ,

the component that has this functionality is https://github.com/b-m-f/WirtBot/blob/master/Interface/src/components/DeviceRow.vue .

I would begin looking on the function that the IP input triggers!

**Comment by b-m-f** [comment]
Fixed in #88
